services:
  db_migrate:
    container_name: db_migrate
    tty: true
    command: sh -c 'npm run db:drop && npm run db:create && npm run db:generate && npm run db:push && npm run db:seed'
    # command: echo skip
    # develop:
    #   watch:
    #     - action: rebuild
    #       path: ./src
    #       target: ./src
    #       ignore:
    #         - node_modules/
    depends_on:
      db:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    networks:
      - project_network

volumes:
  cosc680-db:

networks:
  project_network:
